name: Setup Python Environment

description: Install Python with Poetry, and create the virtual environment

inputs:
  python-version:
    description: "Python version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-in-project: true

    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"

    - name: Install dependencies
      shell: bash
      run: |
        poetry config virtualenvs.in-project true
        poetry install --no-root
