name: Run tests

on: 
  workflow_call:
    inputs:
      python-version:
        description: Python version
        required: true
        type: string
      enable-linting:
        description: Whether to check code formatting with Black
        required: false
        type: boolean
        default: true
      enable-tests:
        description: Whether to run unit tests with Unittest
        required: false
        type: boolean
        default: true
      enable-type-checks:
        description: Whether to run type checks with MyPy
        required: false
        type: boolean
        default: true
      enable-pytest:
        description: Whether to run Pytest
        required: false
        type: boolean
        default: true
      additional-param-pytest:
        description: Whether to run Pytest with parameter
        required: false
        type: string
        default: ""
      additional-param-mypy:
        description: Whether to run Mypy with parameter
        required: false
        type: string
        default: ""
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: guidion-digital/python-workflows/.github/actions/setup-poetry-environment@master
        name: Setup Python environment
        with:
          python-version: ${{ inputs.python-version}}

      - name: Mypy
        if: ${{ inputs.enable-type-checks }}
        shell: bash
        run: poetry run mypy . ${{ inputs.additional-param-mypy }}

      - name: Black
        if: ${{ inputs.enable-linting }}
        shell: bash
        run: poetry run black . --check

      - name: Unit tests
        if: ${{ inputs.enable-tests }}
        shell: bash
        run: poetry run python -m unittest

      - name: Pytests
        if: ${{ inputs.enable-pytest }}
        shell: bash
        run: poetry run pytest -v ${{ inputs.additional-param-mypy }}
